name: main-latest

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:

  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare release ID
        id: prep
        run: |
          echo "created=$(date -u +'%Y%m%d-%H%M')" >> $GITHUB_OUTPUT

    outputs:
      created: ${{ steps.prep.outputs.created }} # refer to as ${{needs.prepare.outputs.created}}

  build:
    needs: [ prepare ]
    runs-on: ${{ matrix.arch.runner }}
    strategy:
      fail-fast: false # let other jobs try to complete if one fails
      matrix:
        arch: [ { name: 'amd64', runner: 'ubuntu-latest' } , { name: 'arm64', runner: 'ubuntu-24.04-arm' } ]
        distro: [ { id: "el8", image: 'rockylinux/rockylinux:8' }, { id: "el9", image: 'rockylinux/rockylinux:9' }, { id: "el10", image: 'rockylinux/rockylinux:10' } ]
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Build ${{ matrix.arch.name }} ${{ matrix.distro.image }}
        uses: docker/build-push-action@v6
        timeout-minutes: 180
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/${{ matrix.arch.name }}
          load: true
          pull: true # bring in updated versions of preexisting GH images
          push: false
          tags: k8s-worker-containerd:${{ matrix.arch.name }}
          cache-from: type=gha,scope=${{ matrix.arch.name }}_${{ matrix.distro.image }}
          cache-to: type=gha,scope=${{ matrix.arch.name }}_${{ matrix.distro.image }}
          build-args: |
            PACKAGE_VERSION=${{needs.prepare.outputs.created}}
            BASE_IMAGE=${{ matrix.distro.image }}
            OS_ARCH=${{ matrix.arch.name }}

      - name: Extract artifacts from docker ${{ matrix.arch.name }} ${{ matrix.distro.image }}
        run: docker cp $(docker create --rm k8s-worker-containerd:${{ matrix.arch.name }}):/out ./

      - name: Upload rpm as artifact ${{ matrix.arch.name }} ${{ matrix.distro.id }}
        uses: actions/upload-artifact@v4
        with:
          name: rpm-${{ matrix.arch.name }}-${{ matrix.distro.id }}
          path: out/*.rpm

      - name: Upload tarball as artifact ${{ matrix.arch.name }} ${{ matrix.distro.id }}
        uses: actions/upload-artifact@v4
        with:
          name: tarball-${{ matrix.arch.name }}-${{ matrix.distro.id }}
          path: out/*.tar.gz


  release:
    needs: [ prepare, build ] # depend on the previous jobs...
    #if: "${{ always() }}" # ... but run even if (some of) them failed.
    runs-on: ubuntu-latest
    steps:
      # Download the built artifacts from GH artifacts.  
      - uses: actions/download-artifact@v4
        name: Download rpm artifacts
        with:
          pattern: rpm-*
          merge-multiple: true
          path: out

      - uses: actions/download-artifact@v4
        name: Download tarball artifacts
        with:
          pattern: tarball-*
          merge-multiple: true
          path: out

      - name: List artifacts downloaded
        run: |
          ls -lahtR

      # Release the artifacts into GitHub Releases
      - name: "GH specific release"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{needs.prepare.outputs.created}}"
          prerelease: false
          title: "${{needs.prepare.outputs.created}}"
          files: |
            out/*.rpm
            out/*.tar.gz
